### ISSUE TITLE
Compilation with Qt5.3

### ISSUE THREAD

**Issue by rarog** [commontk/QtSOAP#5]
Is compilation with Qt5.3 possible?
Compilation via QtCreator seems to make some problems. Is the only way to run ./configure.sh or configure.bat and then to run qmake?

**Comment by jcfr** [comment]
1. Compiling this project is supported using cmake.
2. it is not actively maintained, it is originally a fork of https://github.com/qtproject/qt-solutions/tree/master/qtsoap
